---
version: '3'

services:
  app:
    # Comment to use dockerhub image
    build:
      context: .
      dockerfile: contrib/docker/Dockerfile
    image: ismaelmds/pixelfed
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - .:/var/www
    networks:
      - external
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
      - migration
    labels:
      - "traefik.http.routers.app.rule=Host(`contrariamente.local`)"
      - "traefik.http.routers.app.tls=true"

  migration:
      build:
        context: .
        dockerfile: contrib/docker/Dockerfile
      image: ismaelmds/pixelfed
      env_file:
          - .env.docker
      volumes:
        - .:/var/www
      networks:
          - external
      depends_on:
          - db
          - redis
      command: bash -c "sleep 20 && php artisan migrate --force && composer install --prefer-dist --no-interaction --no-ansi && ln -s public html"

  ## DB and Cache
  db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - external
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.docker
    ports:
        - 3306:3306

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    env_file:
      - .env.docker
    networks:
      - external

  traefik:
    image: "traefik:v2.0"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - app

networks:
  external:
    driver: bridge
